# Generated by Django 4.1.1 on 2022-11-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prewedding',
            options={'ordering': ('publish',)},
        ),
    ]
